export const pagination = {
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  userSelect: 'none',
  mt:'7',
  'li:nth-last-of-type(2)': {
    borderRadius: '0 50% 50% 0',
  },
  '.rc-pagination-item': {
    a: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      bg: 'none',
      color: 'disabled_text',
      fontSize: '10px',
      h: 'full',
      _hover: {
        bg: 'primary.100',
        borderRadius: '2xl',
        color: 'main_white',
      },
    },
    px: '3px',
    py: '2px',
    h: '6',
    m: '0',
    border: 'none',
    bg: 'grey.pagination_bg',
    borderRadius: 'none',
  },
  '.rc-pagination-item-1': {
    borderRadius: '50% 0 0 50%',
  },
  '.rc-pagination-item-active': {
    a: {
      bg: 'primary.100',
      borderRadius: '2xl',
      color: 'main_white',
    },
  },
  '.rc-pagination-jump-next': {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    h: '6',
    bg: 'grey.pagination_bg',
    m: '0',
    borderRadius: 'none',
  },
  '.rc-pagination-jump-prev': {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    h: '6',
    bg: 'grey.pagination_bg',
    m: '0',
    borderRadius: 'none',
  },
  '.rc-pagination-prev': {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    h: '5',
    minW: '5',
    mr: '3',
    bg: 'primary.100',
    borderRadius: '50%',
    color: 'main_white',
    cursor: 'pointer',
  },
  '.rc-pagination-next': {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    h: '5',
    minW: '5',
    ml: '3',
    bg: 'primary.100',
    borderRadius: '50%',
    color: 'main_white',
    cursor: 'pointer',
  },
  '.rc-pagination-disabled': {
    cursor: 'auto',
    bg: 'grey.pagination_bg',
    color: 'grey.pagination_disabled',
  },
}