git:
  tagName: v${version}
  requireBranch: release
  requireUpstream: false
  commit: true
  tag: true
  push: true
github:
  release: true
plugins:
  "@release-it/conventional-changelog":
    infile: CHANGELOG.md
    preset: conventionalcommits
npm:
  publish: false
