name: PR branch deployment
on:
  push:
    branches:
      - master

jobs:
  build:
    name: test build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
    - name: install deps
      run: npm ci
    - name: lint
      run: npm run lint
    - name: build
      run: npm run build
    - name: export static website
      run: npm run export
    - uses: shallwefootball/s3-upload-action@master
      with:
        aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        aws_bucket: 'website-master-cryptogic'
        source_dir: 'out'
